# File: docker-compose.yml
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_port_listener 5672" ]
      interval: 5s
      timeout: 5s
      retries: 30

  customer-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: customer_service
    ports:
      - "8081:8081"
    environment:
      - QUARKUS_RABBITMQ_HOST=rabbitmq
      - RABBIT_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./customer_service/openapi:/app/openapi  # Mount generated files to host

  merchant-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: merchant_service
    ports:
      - "8082:8082"
    environment:
      - QUARKUS_RABBITMQ_HOST=rabbitmq
      - RABBIT_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./merchant_service/openapi:/app/openapi

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: payment_service
    ports:
      - "8083:8083"
    environment:
      - QUARKUS_RABBITMQ_HOST=rabbitmq
      - RABBIT_HOST=rabbitmq
      - BANK_API_KEY=${BANK_API_KEY}
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./payment_service/openapi:/app/openapi

  token-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: token_service
    ports:
      - "8084:8084"
    environment:
      - QUARKUS_RABBITMQ_HOST=rabbitmq
      - RABBIT_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./token_service/openapi:/app/openapi

  manager-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: manager_service
    ports:
      - "8085:8085"
    environment:
      - QUARKUS_RABBITMQ_HOST=rabbitmq
      - RABBIT_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./manager_service/openapi:/app/openapi   # assuming manager_service exists in root