services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_port_listener 5672" ]
      interval: 5s
      timeout: 5s
      retries: 30

  dtu-pay:
    build:
      context: ./simple_dtu_pay_service
    ports:
      - "8080:8080"
    environment:
      RABBIT_HOST: rabbitmq
      BANK_API_KEY: eagle0192
    depends_on:
      rabbitmq:
        condition: service_healthy
